#include <stdio.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdint.h>
#include <cstring>
#include <sys/ioctl.h>
#include <linux/spi/spidev.h>

#include "Logging.h"
#include <chrono>
#include <thread>
#include <mutex>
#include <atomic>
#include <string>
#include <queue>
#include <condition_variable>
#include <algorithm>
#include <functional>